name: expense_tracker
description: An app to track and note daily expense.
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter        
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  go_router: ^6.0.1
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.1.0+1

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/